from .jexl import JEXL
from .extended_grammar import ExtendedGrammar
import random
import math


class JexlExtended(JEXL):
    def __init__(self, context=None):
        super().__init__(context=context)

        super().add_function("string", ExtendedGrammar.to_string)
        super().add_function("$string", ExtendedGrammar.to_string)
        super().add_transform("toString", ExtendedGrammar.to_string)
        super().add_transform("string", ExtendedGrammar.to_string)
        super().add_function("length", ExtendedGrammar.length)
        super().add_function("$length", ExtendedGrammar.length)
        super().add_transform("length", ExtendedGrammar.length)
        super().add_function("count", ExtendedGrammar.length)
        super().add_function("$count", ExtendedGrammar.length)
        super().add_transform("count", ExtendedGrammar.length)
        super().add_function("size", ExtendedGrammar.length)
        super().add_function("$size", ExtendedGrammar.length)
        super().add_transform("size", ExtendedGrammar.length)
        super().add_function("substring", ExtendedGrammar.substring)
        super().add_function("$substring", ExtendedGrammar.substring)
        super().add_transform("substring", ExtendedGrammar.substring)
        super().add_function("substringBefore", ExtendedGrammar.substring_before)
        super().add_function("$substringBefore", ExtendedGrammar.substring_before)
        super().add_transform("substringBefore", ExtendedGrammar.substring_before)
        super().add_function("substringAfter", ExtendedGrammar.substring_after)
        super().add_function("$substringAfter", ExtendedGrammar.substring_after)
        super().add_transform("substringAfter", ExtendedGrammar.substring_after)
        super().add_function("uppercase", ExtendedGrammar.uppercase)
        super().add_function("$uppercase", ExtendedGrammar.uppercase)
        super().add_transform("uppercase", ExtendedGrammar.uppercase)
        super().add_function("upper", ExtendedGrammar.uppercase)
        super().add_function("$upper", ExtendedGrammar.uppercase)
        super().add_transform("upper", ExtendedGrammar.uppercase)
        super().add_function("lowercase", ExtendedGrammar.lowercase)
        super().add_function("$lowercase", ExtendedGrammar.lowercase)
        super().add_transform("lowercase", ExtendedGrammar.lowercase)
        super().add_function("lower", ExtendedGrammar.lowercase)
        super().add_function("$lower", ExtendedGrammar.lowercase)
        super().add_transform("lower", ExtendedGrammar.lowercase)
        super().add_function("camelCase", ExtendedGrammar.camel_case)
        super().add_function("$camelCase", ExtendedGrammar.camel_case)
        super().add_transform("camelCase", ExtendedGrammar.camel_case)
        super().add_transform("camelcase", ExtendedGrammar.camel_case)
        super().add_transform("toCamelCase", ExtendedGrammar.camel_case)
        super().add_function("pascalCase", ExtendedGrammar.pascal_case)
        super().add_function("$pascalCase", ExtendedGrammar.pascal_case)
        super().add_transform("pascalCase", ExtendedGrammar.pascal_case)
        super().add_transform("pascalcase", ExtendedGrammar.pascal_case)
        super().add_transform("toPascalCase", ExtendedGrammar.pascal_case)
        super().add_function("trim", ExtendedGrammar.trim)
        super().add_function("$trim", ExtendedGrammar.trim)
        super().add_transform("trim", ExtendedGrammar.trim)
        super().add_function("pad", ExtendedGrammar.pad)
        super().add_function("$pad", ExtendedGrammar.pad)
        super().add_transform("pad", ExtendedGrammar.pad)
        super().add_function("contains", ExtendedGrammar.contains)
        super().add_function("$contains", ExtendedGrammar.contains)
        super().add_transform("contains", ExtendedGrammar.contains)
        super().add_function("includes", ExtendedGrammar.contains)
        super().add_function("$includes", ExtendedGrammar.contains)
        super().add_transform("includes", ExtendedGrammar.contains)
